language: node_js

sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true

cache: yarn

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --prefer-offline --frozen-lockfile

script:
  - yarn test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
